2021-04-29 22:13:33,671 ERROR: Exception on /reset_password_request [POST] [in c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Google Drive\Coding\Web Development\microblog\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "D:\Google Drive\Coding\Web Development\microblog\app\email.py", line 16, in send_password_reset_email
    text_body=render_template('email/reset_password.txt', user=user, token=token),
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\loaders.py", line 115, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 60, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 89, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: email/reset_password.txt
2021-04-29 22:14:34,479 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:14:40,220 ERROR: Exception on /reset_password_request [POST] [in c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Google Drive\Coding\Web Development\microblog\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "D:\Google Drive\Coding\Web Development\microblog\app\email.py", line 17, in send_password_reset_email
    html_body=render_template('email/reset_password.html', user=user, token=token))
TypeError: send_email() missing 1 required positional argument: 'recipients'
2021-04-29 22:16:47,304 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:21:17,555 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:24:44,392 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:41:02,538 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:46]
2021-04-29 22:44:01,983 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:46]
2021-04-29 22:49:46,936 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:46]
2021-04-29 22:50:38,737 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:46]
2021-04-29 22:53:49,775 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:46]
2021-04-29 22:56:42,239 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:46]
2021-04-29 23:03:48,798 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:47]
2021-04-29 23:04:06,495 ERROR: Exception on /reset_password_request [POST] [in c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Google Drive\Coding\Web Development\microblog\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "D:\Google Drive\Coding\Web Development\microblog\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\Google Drive\Coding\Web Development\microblog\app\models.py", line 67, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2021-04-29 23:06:13,269 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:47]
2021-04-29 23:06:46,153 ERROR: Exception on /reset_password_request [POST] [in c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Google Drive\Coding\Web Development\microblog\app\routes.py", line 103, in reset_password_request
    send_password_reset_email(user)
  File "D:\Google Drive\Coding\Web Development\microblog\app\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "D:\Google Drive\Coding\Web Development\microblog\app\models.py", line 67, in get_reset_password_token
    app.config['SECRET_KEY'], algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'
2021-04-29 23:07:41,073 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:47]
