2021-04-25 22:37:10,926 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 22:37:14,244 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 22:53:33,135 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 22:54:52,570 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 22:55:54,110 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 22:57:16,013 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 22:57:27,146 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 22:58:27,595 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:00:08,291 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:06:41,437 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:08:24,942 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:08:33,743 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:09:04,582 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:09:18,504 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:09:35,995 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:09:39,801 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:10:21,996 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:14:53,417 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-25 23:15:29,588 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-26 10:29:46,499 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-26 10:31:18,619 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-26 10:31:28,021 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-26 10:31:33,467 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-27 11:10:02,346 INFO: Microblog startup [in C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-27 11:10:50,284 ERROR: Exception on /user/Susan [GET] [in c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\routes.py", line 80, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2021-04-27 11:10:54,274 ERROR: Exception on /user/john [GET] [in c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\routes.py", line 80, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2021-04-27 11:11:10,160 ERROR: Exception on /user/Susan [GET] [in c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\routes.py", line 80, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2021-04-27 11:11:12,637 ERROR: Exception on /user/Susan [GET] [in c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\abrow\google drive\coding\web development\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Abrow\Google Drive\Coding\Web Development\microblog\app\routes.py", line 80, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
