2021-04-29 12:41:58,585 ERROR: Exception on / [GET] [in c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Google Drive\Coding\Web Development\microblog\app\routes.py", line 28, in index
    posts = current_user.followed.posts().all()
AttributeError: 'AppenderBaseQuery' object has no attribute 'posts'
2021-04-29 12:44:07,111 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-29 12:57:58,481 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-29 12:58:03,617 ERROR: Exception on /index [GET] [in c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\Google Drive\Coding\Web Development\microblog\app\routes.py", line 28, in index
    posts = current_user.followed.posts().paginate(
AttributeError: 'AppenderBaseQuery' object has no attribute 'posts'
2021-04-29 12:58:31,162 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-29 13:17:39,611 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-29 13:18:02,442 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-29 13:26:35,719 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:42]
2021-04-29 13:35:39,013 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:08:50,900 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:09:02,068 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:11:33,000 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:12:14,744 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
2021-04-29 22:12:17,996 ERROR: Exception on /login [GET] [in c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Google Drive\Coding\Web Development\microblog\app\routes.py", line 53, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\Google Drive\Coding\Web Development\microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Google Drive\Coding\Web Development\microblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "D:\Google Drive\Coding\Web Development\microblog\app\templates\login.html", line 26, in block "content"
    <a href="{{ url_for('request_password_request') }}">Click to Reset It</a>
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\abrow\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'request_password_request'. Did you mean 'reset_password_request' instead?
2021-04-29 22:13:08,947 INFO: Microblog startup [in D:\Google Drive\Coding\Web Development\microblog\app\__init__.py:44]
